let airlineNameInput = document.getElementById("airlineName");
let airlineIndexInput = document.getElementById("airlineIndex");
let airlineForm = document.getElementById("airlineForm");
let addBtn = document.getElementById("addBtn");
let updateBtn = document.getElementById("updateBtn");
let airlinesList = document.getElementById("airlinesList");
let editBtn = document.getElementById("editBtn");
let deleteBtn = document.getElementById("deleteBtn");

function loadAirlines() {
  let airlines = JSON.parse(localStorage.getItem("airlines")) || [
    {
      id: "1",
      name: "Air India",
    },
    {
      id: "2",
      name: "Indigo",
    },
  ];
  displayAirlines(airlines);
}

// Delete airline
function deleteAirline(id) {
  const airlines = JSON.parse(localStorage.getItem("airlines")) || [];
  const updatedAirlines = airlines.filter((airline) => airline.id !== id);
  localStorage.setItem("airlines", JSON.stringify(updatedAirlines));
  loadAirlines();
}

// Edit airline
function editAirline(id) {
  const airlines = JSON.parse(localStorage.getItem("airlines")) || [];
  const airline = airlines.find((airline) => airline.id === id);
  if (airline) {
    airlineNameInput.value = airline.name;
    airlineIndexInput.value = id;
    addBtn.classList.add("d-none");
    updateBtn.classList.remove("d-none");
  }
}

// Display airlines in the table
function displayAirlines(airlines) {
  airlinesList.innerHTML = "";
  airlines.forEach((airline) => {
    const row = document.createElement("tr");

    row.innerHTML = `
        <td>${airline.id}</td>
        <td>${airline.name}</td>
        <td>
          <button class="btn btn-warning btn-sm" onclick="editAirline('${airline.id}')">Edit</button>
          <button class="btn btn-danger btn-sm" onclick="deleteAirline('${airline.id}')">Delete</button>
        </td>
      `;
    airlinesList.appendChild(row);
  });
}

function generateUniqueId() {
  return Math.random().toString(36);
}

function resetForm() {
  airlineNameInput.value = "";
  airlineIndexInput.value = "";
  addBtn.classList.remove("d-none");
  updateBtn.classList.add("d-none");
}

// Save a new or updated airline
function saveAirline(event) {
  event.preventDefault();
  const airlines = JSON.parse(localStorage.getItem("airlines")) || [];
  const airlineName = airlineNameInput.value.trim();
  const id = generateUniqueId();

  // Add new airline with a unique ID generated by Math
  airlines.push({ id, name: airlineName });

  localStorage.setItem("airlines", JSON.stringify(airlines));
  loadAirlines();
  resetForm();
}

// Save a new or updated airline
function updateAirline(event) {
  event.preventDefault();
  const airlines = JSON.parse(localStorage.getItem("airlines")) || [];
  const airlineName = airlineNameInput.value.trim();
  const id = airlineIndexInput.value;

  if (airlineIndexInput.value) {
    // Update existing airline by ID
    const airline = airlines.find((airline) => airline.id === id);
    if (airline) {
      airline.name = airlineName;
    }
  }

  localStorage.setItem("airlines", JSON.stringify(airlines));
  loadAirlines();
  resetForm();
}

// Event listeners
airlineForm.addEventListener("submit", saveAirline);
updateBtn.addEventListener("click", updateAirline);

loadAirlines();
